### PR TITLE
Add Scan to StockAlertBot

### PR DESCRIPTION
**Pull request by Alienwarez123**
I'm very new to npm but this seems to work for me, I made it to see if I can get a founders card from them since I heard they are pretty cheap and there was a 3070 founders edition yesterday morning that got released. This looks about right to me but i'm open to editing it :)

### CODE REVIEW

**Comment by Prince25** [comment]
Hi. Thanks for taking the time to add Scan and IFTTT webhook. Having IFTTT is basically like having everything else. lol
One question for Scan though, does the bot work on items on Scan for you? At least in the US, they seem to have Cloudflare protection so HTTP requests do not work.

**Comment by Prince25** [comment]
As you can see in the fetched html:
image

**Comment by Alienwarez123** [comment]
Yeah they work fine, I didn't even know they had cloudflare
image

**Comment by Prince25** [comment]
That's weird. I get Cloudflare whenever I try running it. Maybe they're filtering out non-UK based IPs or something? We need more tests. @Jeisonx could you give it a try?

**Comment by Prince25** [comment]
I'm looking at bypassing Cloudflare for a different project. It seems to have updated recently so most solutions do not work atm.

**Comment by Jeisonx** [comment]
> That's weird. I get Cloudflare whenever I try running it. Maybe they're filtering out non-UK based IPs or something? We need more tests. @Jeisonx could you give it a try?
 
I do also believe that they're filtering out non UK based IPs. Just by opening https://www.scan.co.uk on my browser I get Cloudflare. Running the project has the same result, status code 403.

**Comment by Prince25** [comment]
I will remove Scan for now and add the IFTTT feature. I suggest you create another PR request just for Scan. In the future, try to make a PR request for each feature 😄

**Pull request merged**
